name: Record Douyin & Upload

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
   
    env:
      # 👉 Điền link stream cố định ở đây (ưu tiên URL PC)
      STREAM_URL: "https://live.douyin.com/39766954060"
      # Giới hạn thời lượng để runner không treo vô hạn
      MAX_MINUTES: "480"
      PYTHONIOENCODING: "utf-8"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build DouyinLiveRecorder image
        run: docker build -t dlr:latest .

      - name: Prepare output folders
        run: mkdir -p downloads logs

      - name: Run recorder (feed URL via stdin)
        run: |
          set -e
          timeout "$(( ${MAX_MINUTES} * 60 ))" \
            docker run --rm \
              -v "$PWD/downloads":/app/downloads \
              -v "$PWD/logs":/app/logs \
              -e PYTHONIOENCODING="$PYTHONIOENCODING" \
              dlr:latest \
              bash -lc '
                echo "Booting recorder..."
                # bơm URL vào stdin -> tránh prompt tương tác
                printf "%s\n" "$STREAM_URL" | python3 main.py || true
              '

      - name: List recorded files
        run: |
          echo "downloads:"
          ls -lah downloads || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: recording-${{ github.run_id }}
          path: |
            downloads/**/*
            logs/**/*
          if-no-files-found: warn
          compression-level: 0
