name: Record Douyin & Upload

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    env:
      STREAM_URL: "https://live.douyin.com/39766954060"   # 👉 điền link stream cố định ở đây
      MAX_MINUTES: "480"                           # giới hạn tối đa phút, có thể đổi
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build DouyinLiveRecorder image
        run: docker build -t dlr:latest .

      - name: Prepare output folders
        run: mkdir -p downloads logs

      - name: Run recorder
        run: |
          timeout "$(( ${MAX_MINUTES} * 60 ))" \
            docker run --rm \
              -v "$PWD/downloads":/app/downloads \
              -v "$PWD/logs":/app/logs \
              dlr:latest \
              bash -lc '
                # 👇 chỉnh lệnh chạy theo repo. Ví dụ:
                # python3 main.py --url "$STREAM_URL" --once
                if [ -f main.py ]; then
                  python3 main.py || true
                elif [ -f demo.py ]; then
                  python3 demo.py || true
                else
                  echo "Không tìm thấy main.py/demo.py" && exit 1
                fi
              '

      - name: List recorded files
        run: ls -lah downloads || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: recording-${{ github.run_id }}
          path: |
            downloads/**/*
            logs/**/*
          if-no-files-found: warn
          compression-level: 0
